name: ci/cd pbl2

on:
  push:
    branches:
      - "main"

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
      tags:
        description: 'dispatch'

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pbl2-fe:latest

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_PBL2 }}
          username: ${{ secrets.SSH_USERNAME_PBL2 }}
          password: ${{ secrets.SSH_PASSWORD_PBL2 }}
          port: ${{ secrets.SSH_PORT_PBL2 }}
          timeout: 600s
          command_timeout: 600s
          debug: true
          script: |
            set -ex  # 에러 발생 시 즉시 종료 + 실행된 명령어 로그 출력
            docker stop pbl2-fe || true
            docker rm pbl2-fe || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pbl2-fe:latest
            docker network ls | grep -w "mojadol-network" || docker network create mojadol-network
            docker run -d -p 4000:80 --name pbl2-fe --network mojadol-network ${{ secrets.DOCKERHUB_USERNAME }}/pbl2-fe:latest
            docker ps -a
            docker logs --tail=50 pbl2-fe
