name: ci/cd pbl2

on:
  push:
    branches:
      - "main"

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
      tags:
        description: 'dispatch'

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload 코드 파일 전송
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST_PBL2 }}
          username: ${{ secrets.SSH_USERNAME_PBL2 }}
          password: ${{ secrets.SSH_PASSWORD_PBL2 }}
          port: ${{ secrets.SSH_PORT_PBL2 }}
          source: "."
          target: "/home/bgt/pbl2"
