name: ci/cd pbl2

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies & Build Frontend
        run: |
          cd
          cd /home/bgt/pbl2/fe
          npm install
          npm run build

      - name: Send Build Files to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST_PBL2 }}
          username: ${{ secrets.SSH_USERNAME_PBL2 }}
          password: ${{ secrets.SSH_PASSWORD_PBL2 }}
          port: ${{ secrets.SSH_PORT_PBL2 }}
          source: "fe/build/*"
          target: "/home/bgt/pbl2/fe/build"

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_PBL2 }}
          username: ${{ secrets.SSH_USERNAME_PBL2 }}
          password: ${{ secrets.SSH_PASSWORD_PBL2 }}
          port: ${{ secrets.SSH_PORT_PBL2 }}
          timeout: 600s
          command_timeout: 600s
          debug: true
          script: |
            set -ex
            cd /home/bgt/pbl2/fe

            # Nginx 컨테이너에 복사 후 재시작
            docker cp /home/bgt/pbl2/fe/build/. pbl2-nginx:/usr/share/nginx/html/
            docker restart pbl2-nginx

            docker ps -a
            docker logs --tail=50 pbl2-nginx
