name: ci/cd pbl2

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies & Build Frontend
        run: |
          npm ci
          npm run build

      - name: Deploy to Server via SSH & Rsync
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_PBL2 }}
          username: ${{ secrets.SSH_USERNAME_PBL2 }}
          password: ${{ secrets.SSH_PASSWORD_PBL2 }}
          port: ${{ secrets.SSH_PORT_PBL2 }}
          timeout: 600s
          command_timeout: 600s
          script: |
            set -ex

            # 파일 전송 (scp 사용)
            scp -P ${{ secrets.SSH_PORT_PBL2 }} -r ./build/* ${{ secrets.SSH_USERNAME_PBL2 }}@${{ secrets.SSH_HOST_PBL2 }}:/home/bgt/pbl2/fe/
            
            # Docker 컨테이너 재시작
            docker restart pbl2-nginx

            # 로그 확인
            docker ps -a
            docker logs --tail=50 pbl2-nginx
