name: ci/cd pbl2

on:
  push:
    branches:
      - "main"

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_PBL2 }}
          username: ${{ secrets.SSH_USERNAME_PBL2 }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PBL2 }}
          port: ${{ secrets.SSH_PORT_PBL2 }}
          script: |
            set -ex
            mkdir -p /home/bgt/pbl2/fe  # 배포 폴더 생성
            rm -rf /home/bgt/pbl2/fe/*  # 기존 파일 삭제
      
      - name: Upload Build Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_PBL2 }}
          username: ${{ secrets.SSH_USERNAME_PBL2 }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PBL2 }}
          port: ${{ secrets.SSH_PORT_PBL2 }}
          source: "./build/*"
          target: "/home/bgt/pbl2/fe"
      
      - name: Restart Docker
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_PBL2 }}
          username: ${{ secrets.SSH_USERNAME_PBL2 }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PBL2 }}
          port: ${{ secrets.SSH_PORT_PBL2 }}
          script: |
            set -ex
            docker restart pbl2-nginx  # 컨테이너 재시작
            docker logs --tail=50 pbl2-nginx  # 로그 확인

